### ISSUE TITLE
Cannot generate

### ISSUE THREAD

**Issue by fizzys0da** [k11dd00/oniongen#1]
Reports:
`Traceback (most recent call last):
  File "C:\Users\*****\Downloads\oniongen\oniongen.py", line 39, in <module>
    from cmd.cmdstrategy import CommandStrategy
  File "C:\Users\*****\Downloads\oniongen\cmd\cmdstrategy.py", line 27, in <module>
    from generatecmd import GenerateCommand
ModuleNotFoundError: No module named 'generatecmd'`

**Comment by Zeal0usD** [comment]
can't find this module anywhere
